import { ImageResponse } from "next/og";
import { POSTS } from "../../../_content/site";

// A real 1200x630 PNG per article, generated by next/og, at a STABLE url.
//
// This began as an opengraph-image.tsx, which is the idiomatic place for it —
// but Next appends a build hash to that route (/opengraph-image-fx5gi7), so the
// path cannot be written by hand and the blog index cards pointed at a 404
// (caught by curling the built server, not by the build, which reported fine).
// A route handler keeps the url predictable at /blog/<slug>/cover, which lets
// one generated PNG serve BOTH the social preview and the index card rather
// than generating the same image twice at two addresses.
//
// Every post previously fell back to the site-wide card, so a WhatsApp or
// LinkedIn share of the pricing article and the template article were pixel
// identical — the preview told a reader nothing about which piece they were
// being sent, which is most of what a preview is for.
//
// Generated rather than drawn: a static asset per post is one more thing to
// make, forget, and let drift out of sync with a retitled article. This reads
// the title from the same POSTS array the page does, so it cannot disagree with
// the page, and every future post gets a card for free.
const size = { width: 1200, height: 630 };

// Prerendered for every post at build time; nothing here varies per request.
export const dynamic = "force-static";
export function generateStaticParams() {
  return POSTS.map(p => ({ slug: p.slug }));
}

// Each article gets its own colourway, picked deterministically from the slug
// so a card looks the same on every rebuild but different from its neighbours.
// All four stay inside the brand ramp (#0668D6 → #8a5cff), so the set reads as
// one family rather than a rainbow.
const RAMPS = [
  ["#0668D6", "#0783fd", "#5b6dff"],
  ["#0783fd", "#4f6bff", "#8a5cff"],
  ["#063e7e", "#0668D6", "#4f49c7"],
  ["#2a96ff", "#5b6dff", "#6a5cff"],
];
const rampFor = (slug: string) =>
  RAMPS[[...slug].reduce((n, c) => n + c.charCodeAt(0), 0) % RAMPS.length];

export async function GET(_req: Request, { params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const post = POSTS.find(p => p.slug === slug);
  const title = post?.title ?? "Talko AI";
  const [a, b, c] = rampFor(slug);

  return new ImageResponse(
    (
      <div
        style={{
          height: "100%", width: "100%", display: "flex", flexDirection: "column",
          justifyContent: "space-between", padding: "76px 84px",
          background: `linear-gradient(120deg, ${a} 0%, ${b} 52%, ${c} 100%)`,
          color: "white", fontFamily: "sans-serif",
        }}
      >
        <div style={{ display: "flex", alignItems: "center", gap: 18 }}>
          <div style={{ fontSize: 34, fontWeight: 800, letterSpacing: -0.5 }}>Talko AI</div>
          {post?.category && (
            <div style={{
              fontSize: 21, fontWeight: 700, padding: "7px 18px", borderRadius: 999,
              background: "rgba(255,255,255,0.18)", border: "1px solid rgba(255,255,255,0.32)",
            }}>{post.category}</div>
          )}
        </div>

        {/* Long titles are the common case here, so the size steps down rather
            than overflowing or being truncated mid-word. */}
        <div style={{
          fontSize: title.length > 64 ? 60 : 72,
          fontWeight: 800, lineHeight: 1.06, letterSpacing: -1.5, maxWidth: 1000,
        }}>{title}</div>

        <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", fontSize: 24, opacity: 0.93 }}>
          <div style={{ fontWeight: 700 }}>thetalko.in</div>
          <div>{[post?.date, post?.readTime].filter(Boolean).join("  ·  ")}</div>
        </div>
      </div>
    ),
    { ...size },
  );
}
